import type { TimelineStage } from './timelineTypes';

export const professionalStages: TimelineStage[] = [
  {
    id: 'alfa-soft-junior',
    year: 2014,
    logoSrc: '/logos/alfasoft.jpg',
    category: 'experience',
    translationKey: 'timeline.stages.alfaSoftJunior',
  },
  {
    id: 'virtual-softwares-junior',
    year: 2015,
    logoSrc: '/logos/virtual.png',
    category: 'experience',
    translationKey: 'timeline.stages.virtualSoftwaresJunior',
  },
  {
    id: 'virtual-softwares-pleno',
    year: 2017,
    logoSrc: '/logos/virtual.png',
    category: 'experience',
    translationKey: 'timeline.stages.virtualSoftwaresPleno',
  },
  {
    id: 'quiver-programador-senior',
    year: 2018,
    logoSrc: '/logos/quiver.png',
    category: 'experience',
    translationKey: 'timeline.stages.quiverProgramadorSenior',
  },
  {
    id: 'quiver-analyst',
    year: 2019,
    logoSrc: '/logos/quiver.png',
    category: 'experience',
    translationKey: 'timeline.stages.quiverAnalyst',
  },
  {
    id: 'quiver-specialist',
    year: 2020,
    logoSrc: '/logos/quiver.png',
    category: 'experience',
    translationKey: 'timeline.stages.quiverSpecialist',
  },
  {
    id: 'docato-tech',
    year: 2020,
    logoSrc: '/logos/docato.png',
    category: 'experience',
    translationKey: 'timeline.stages.docatoTechLead',
  },
  {
    id: 'docato-head',
    year: 2021,
    logoSrc: '/logos/docato.png',
    category: 'experience',
    translationKey: 'timeline.stages.docatoHead',
  },
  {
    id: 'comunidade-crowd',
    year: 2021,
    logoSrc: '/logos/crowd.jpeg',
    category: 'experience',
    translationKey: 'timeline.stages.comunidadeCrowd',
  },
  {
    id: 'kwan',
    year: 2022,
    logoSrc: '/logos/kwan.png',
    category: 'experience',
    translationKey: 'timeline.stages.kwan',
  },
  {
    id: 'prime-nearshore',
    year: 2022,
    logoSrc: '/logos/prime_nearshore_logo.jpeg',
    category: 'experience',
    translationKey: 'timeline.stages.primeNearshore',
  },
];

export const learningStages: TimelineStage[] = [
  {
    id: 'colegio-santana',
    year: 2009,
    logoSrc: '/logos/santana.jpeg',
    category: 'education',
    translationKey: 'timeline.stages.colegioSantana',
  },
  {
    id: 'cert-cebrac-hardware',
    year: 2010,
    logoSrc: '/logos/cebrac.jpeg',
    category: 'certification',
    translationKey: 'timeline.stages.certCebracHardware',
  },
  {
    id: 'cert-exercito-oficial',
    year: 2010,
    logoSrc: '/logos/exercito.svg',
    category: 'certification',
    translationKey: 'timeline.stages.certExercitoOficial',
  },
  {
    id: 'unopar',
    year: 2015,
    logoSrc: '/logos/unopar.png',
    category: 'education',
    translationKey: 'timeline.stages.unopar',
  },
  {
    id: 'pos',
    year: 2019,
    logoSrc: '/logos/universidade-positivo.svg',
    category: 'education',
    translationKey: 'timeline.stages.posGraduation',
  },
  {
    id: 'cert-udemy-unit-testing',
    year: 2022,
    logoSrc: '/logos/udemy.svg',
    category: 'certification',
    translationKey: 'timeline.stages.certUdemyUnitTesting',
  },
  {
    id: 'cert-hackerrank',
    year: 2023,
    logoSrc: '/logos/hackerrank.svg',
    category: 'certification',
    translationKey: 'timeline.stages.certHackerRank',
  },
  {
    id: 'cert-hackerrank-intermediate',
    year: 2023,
    logoSrc: '/logos/hackerrank.svg',
    category: 'certification',
    translationKey: 'timeline.stages.certHackerRankIntermediate',
  },
  {
    id: 'cert-hackerrank-node',
    year: 2023,
    logoSrc: '/logos/hackerrank.svg',
    category: 'certification',
    translationKey: 'timeline.stages.certHackerRankNode',
  },
  {
    id: 'cert-fullcycle-architecture',
    year: 2023,
    logoSrc: '/logos/fullcycle.svg',
    category: 'certification',
    translationKey: 'timeline.stages.certFullCycleArchitecture',
  },
  {
    id: 'cert-fullcycle-ddd',
    year: 2023,
    logoSrc: '/logos/fullcycle.svg',
    category: 'certification',
    translationKey: 'timeline.stages.certFullCycleDDD',
  },
  {
    id: 'cert-fullcycle-solid',
    year: 2023,
    logoSrc: '/logos/fullcycle.svg',
    category: 'certification',
    translationKey: 'timeline.stages.certFullCycleSolid',
  },
  {
    id: 'cert-nestjs',
    year: 2024,
    logoSrc: '/logos/nestjs.svg',
    category: 'certification',
    translationKey: 'timeline.stages.certNest',
  },
];

